=== galsenpro/data_model/iot_testnca_datamodels_v1.0/waterObserved/POI-WaterLevelAndRiverFlow-201711071221.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$id": "http://example.com/example.json",
  "type": "object",
  "properties": {
    "id": {
      "$id": "/properties/id",
      "type": "string",
      "title": "The Id Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "IdOfPointInterest"
      ]
    },
    "type": {
      "$id": "/properties/type",
      "type": "string",
      "title": "The Type Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "PointOfInterest"
      ]
    },
    "name": {
      "$id": "/properties/name",
      "type": "string",
      "title": "The Name Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "Y6042010 - Var-Entrevaux [Pont-levis]"
      ]
    },
    "description": {
      "$id": "/properties/description",
      "type": "string",
      "title": "The Description Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "Description du site Y6042010"
      ]
    },
    "category": {
      "$id": "/properties/category",
      "type": "array",
      "items": {
        "$id": "/properties/category/items",
        "type": "string",
        "title": "The 0 Schema.",
        "description": "An explanation about the purpose of this instance.",
        "default": "",
        "examples": [
          "Numï¿½ro du WaterLevelAndRiverFlow dans le dictionnaire"
        ]
      }
    },
    "dateCreated": {
      "$id": "/properties/dateCreated",
      "type": "string",
      "title": "The Datecreated Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "2016-06-29T15:59:09.22Z"
      ]
    },
    "location": {
      "$id": "/properties/location",
      "type": "object",
      "properties": {
        "type": {
          "$id": "/properties/location/properties/type",
          "type": "string",
          "title": "The Type Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": "",
          "examples": [
            "Point"
          ]
        },
        "coordinates": {
          "$id": "/properties/location/properties/coordinates",
          "type": "array",
          "items": {
            "$id": "/properties/location/properties/coordinates/items",
            "type": "number",
            "title": "The 0 Schema.",
            "description": "An explanation about the purpose of this instance.",
            "default": 0,
            "examples": [
              7.2698564529418945
            ]
          }
        }
      }
    },
    "source": {
      "$id": "/properties/source",
      "type": "string",
      "title": "The Source Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "http://[SourceOfThePOI]"
      ]
    },
    "refSeeAlso": {
      "$id": "/properties/refSeeAlso",
      "type": "array",
      "items": {
        "$id": "/properties/refSeeAlso/items",
        "type": "string",
        "title": "The 0 Schema.",
        "description": "An explanation about the purpose of this instance.",
        "default": "",
        "examples": [
          "WaterLevelAndRiverFlow-201711071221"
        ]
      }
    }
  }
}

=== galsenpro/data_model/iot_testnca_schemas_v1.0/waterObserved/POI-WaterLevelAndRiverFlow-201711071221.json
{
	"id": "IdOfPointInterest",
	"type": "PointOfInterest",
	"name": "Y6042010 - Var-Entrevaux [Pont-levis]",
	"description": "Description du site Y6042010",
	"category": ["Numéro du WaterLevelAndRiverFlow dans le dictionnaire"],
	"dateCreated": "2016-06-29T15:59:09.22Z",
	"location": {
		"type": "Point",
		"coordinates": [7.26985643, 43.69770086]
	},
	"source": "http://[SourceOfThePOI]",
	"refSeeAlso": ["WaterLevelAndRiverFlow-201711071221"]
}
