=== galsenpro/data_model/iot_testnca_schemas_v1.0/Environment/iot_testnca_NoiseLevelObserved-2017-10-31T06_00_00.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$id": "http://example.com/example.json",
  "type": "object",
  "properties": {
    "id": {
      "$id": "/properties/id",
      "type": "string",
      "title": "The Id Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "NoiseLevelObserved-2017-10-31T06:00:00_208402176"
      ]
    },
    "type": {
      "$id": "/properties/type",
      "type": "string",
      "title": "The Type Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "NoiseLevelObserved"
      ]
    },
    "location": {
      "$id": "/properties/location",
      "type": "object",
      "properties": {
        "type": {
          "$id": "/properties/location/properties/type",
          "type": "string",
          "title": "The Type Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": "",
          "examples": [
            "Point"
          ]
        },
        "coordinates": {
          "$id": "/properties/location/properties/coordinates",
          "type": "array",
          "items": {
            "$id": "/properties/location/properties/coordinates/items",
            "type": "number",
            "title": "The 0 Schema.",
            "description": "An explanation about the purpose of this instance.",
            "default": 0,
            "examples": [
              7.15521240234375
            ]
          }
        }
      }
    },
    "dateObserved": {
      "$id": "/properties/dateObserved",
      "type": "string",
      "title": "The Dateobserved Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "2017-10-31T06:00:00/2017-10-31T06:15:00"
      ]
    },
    "measurand": {
      "$id": "/properties/measurand",
      "type": "array",
      "items": {
        "$id": "/properties/measurand/items",
        "type": "string",
        "title": "The 0 Schema.",
        "description": "An explanation about the purpose of this instance.",
        "default": "",
        "examples": [
          "LDEN  | 7587 | Lden"
        ]
      }
    },
    "LDEN": {
      "$id": "/properties/LDEN",
      "type": "integer",
      "title": "The Lden Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": 0,
      "examples": [
        7587
      ]
    },
    "INDIC_ELEM_P1": {
      "$id": "/properties/INDIC_ELEM_P1",
      "type": "string",
      "title": "The Indic_elem_p1 Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "B"
      ]
    },
    "LEQ_P1": {
      "$id": "/properties/LEQ_P1",
      "type": "integer",
      "title": "The Leq_p1 Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": 0,
      "examples": [
        7400
      ]
    },
    "sonometerClass": {
      "$id": "/properties/sonometerClass",
      "type": "string",
      "title": "The Sonometerclass Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "2"
      ]
    },
    "refDevice": {
      "$id": "/properties/refDevice",
      "type": "string",
      "title": "The Refdevice Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "GBOX000014"
      ]
    }
  }
}

=== galsenpro/data_model/iot_testnca_datamodels_v1.0/iot_testnca_NoiseLevelObserved-2017-10-31T06_00_00.json
{
	"id": "NoiseLevelObserved-2017-10-31T06:00:00_208402176",
	"type": "NoiseLevelObserved",
	"location": {
		"type": "Point",
		"coordinates": [7.1552125224843621, 43.660530261510573]
	},
	"dateObserved": "2017-10-31T06:00:00/2017-10-31T06:15:00",
	"measurand": [
		"LDEN  | 7587 | Lden",
		"INDIC_ELEM_P1 | B | Indicateur elementaire",
		"LEQ_P1  | 7400 | Leq période"
		] ,
		"LDEN": 7587,
		"INDIC_ELEM_P1": "B",
		"LEQ_P1": 7400,
		"sonometerClass": "2", 
		"refDevice": "GBOX000014"
}
