=== galsenpro/data_model/schemas_v1.0/PointOfInteraction/iot_schemanca_PointOfInteraction-EVENT-PUBLIC-NCA-8091.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$id": "http://example.com/example.json",
  "type": "object",
  "properties": {
    "id": {
      "$id": "/properties/id",
      "type": "string",
      "title": "The Id Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "EVENT-PUBLIC-NCA-8189"
      ]
    },
    "type": {
      "$id": "/properties/type",
      "type": "string",
      "title": "The Type Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "Event"
      ]
    },
    "name": {
      "$id": "/properties/name",
      "type": "string",
      "title": "The Name Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "(INS)TABLE"
      ]
    },
    "publicAccess": {
      "$id": "/properties/publicAccess",
      "type": "boolean",
      "title": "The Publicaccess Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": false,
      "examples": [
        true
      ]
    },
    "start": {
      "$id": "/properties/start",
      "type": "string",
      "title": "The Start Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "2018-05-13"
      ]
    },
    "end": {
      "$id": "/properties/end",
      "type": "string",
      "title": "The End Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "2018-05-13"
      ]
    },
    "address": {
      "$id": "/properties/address",
      "type": "object",
      "properties": {
        "addressCountry": {
          "$id": "/properties/address/properties/addressCountry",
          "type": "string",
          "title": "The Addresscountry Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": "",
          "examples": [
            "FR"
          ]
        },
        "streetAddress": {
          "$id": "/properties/address/properties/streetAddress",
          "type": "string",
          "title": "The Streetaddress Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": "",
          "examples": [
            "3 rue Paganini"
          ]
        }
      }
    },
    "website": {
      "$id": "/properties/website",
      "type": "array",
      "items": {
        "$id": "/properties/website/items",
        "type": "string",
        "title": "The 0 Schema.",
        "description": "An explanation about the purpose of this instance.",
        "default": "",
        "examples": [
          "http://www.theatredelacite.fr"
        ]
      }
    },
    "phone": {
      "$id": "/properties/phone",
      "type": "string",
      "title": "The Phone Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "+33(0)4 93 16 82 69"
      ]
    },
    "email": {
      "$id": "/properties/email",
      "type": "string",
      "title": "The Email Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "infos@theatredelacite.fr"
      ]
    },
    "profiles": {
      "$id": "/properties/profiles",
      "type": "array",
      "items": {
        "$id": "/properties/profiles/items",
        "type": "string",
        "title": "The 0 Schema.",
        "description": "An explanation about the purpose of this instance.",
        "default": "",
        "examples": [
          "Spectacle"
        ]
      }
    },
    "description": {
      "$id": "/properties/description",
      "type": "array",
      "items": {
        "$id": "/properties/description/items",
        "type": "string",
        "title": "The 0 Schema.",
        "description": "An explanation about the purpose of this instance.",
        "default": "",
        "examples": [
          "TH��TRE DE LA CIT�"
        ]
      }
    },
    "images": {
      "$id": "/properties/images",
      "type": "array",
      "items": {
        "$id": "/properties/images/items",
        "type": "string",
        "title": "The 0 Schema.",
        "description": "An explanation about the purpose of this instance.",
        "default": "",
        "examples": [
          "http://www.nicetourisme.com/public/resources/ref/events/8189/gallery/ins-table_197427.jpg"
        ]
      }
    },
    "location": {
      "$id": "/properties/location",
      "type": "object",
      "properties": {
        "type": {
          "$id": "/properties/location/properties/type",
          "type": "string",
          "title": "The Type Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": "",
          "examples": [
            "Point"
          ]
        },
        "coordinates": {
          "$id": "/properties/location/properties/coordinates",
          "type": "array",
          "items": {
            "$id": "/properties/location/properties/coordinates/items",
            "type": "number",
            "title": "The 0 Schema.",
            "description": "An explanation about the purpose of this instance.",
            "default": 0,
            "examples": [
              7.263889789581299
            ]
          }
        }
      }
    },
    "category": {
      "$id": "/properties/category",
      "type": "array",
      "items": {
        "$id": "/properties/category/items",
        "type": "string",
        "title": "The 0 Schema.",
        "description": "An explanation about the purpose of this instance.",
        "default": "",
        "examples": [
          "Spectacle"
        ]
      }
    },
    "note": {
      "$id": "/properties/note",
      "type": "integer",
      "title": "The Note Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": 0,
      "examples": [
        0
      ]
    },
    "refEntries": {
      "$id": "/properties/refEntries",
      "type": "array",
      "items": {
        "$id": "/properties/refEntries/items",
        "type": "string",
        "title": "The 0 Schema.",
        "description": "An explanation about the purpose of this instance.",
        "default": "",
        "examples": [
          "28810"
        ]
      }
    },
    "dateCreated": {
      "$id": "/properties/dateCreated",
      "type": "string",
      "title": "The Datecreated Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "2017-09-25 10:16:08"
      ]
    },
    "dateUpdated": {
      "$id": "/properties/dateUpdated",
      "type": "string",
      "title": "The Dateupdated Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "2017-09-29 11:26:21"
      ]
    },
    "refRelatedEntity": {
      "$id": "/properties/refRelatedEntity",
      "type": "string",
      "title": "The Refrelatedentity Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "POI-ENTITY-ID"
      ]
    }
  }
}

=== galsenpro/data_model/iot_testnca_datamodels_v1.0/iot_testnca_PointOfInteraction-EVENT-PUBLIC-NCA-8091.json
{
	"id": "EVENT-PUBLIC-NCA-8189",
	"type": "Event",
	"name":"(INS)TABLE",
	"publicAccess": true,
	"start" : "2018-05-13",
	"end": "2018-05-13",
	"address": {
		"addressCountry": "FR",
		"streetAddress": "3 rue Paganini"
	},
	"website": ["http://www.theatredelacite.fr"],
	"phone": "+33(0)4 93 16 82 69",
	"email": "infos@theatredelacite.fr",
	"profiles": ["Spectacle"],
	"description": ["THÉÂTRE DE LA CITÉ",
		"18:00",
		"Dans ce spectacle, des êtres se réunissent, s’aiment, se déchirent, prennent des décisions, regrettent, réfléchissent, s’effondrent, font des choix, rient aux éclats, se rassemblent..."
		],
		"images": ["http://www.nicetourisme.com/public/resources/ref/events/8189/gallery/ins-table_197427.jpg"],
		"location": {
			"type": "Point",
			"coordinates": [
				7.26389,
				43.7018
				]
		},
		"category" : ["Spectacle"],
		"note": 0,
		"refEntries" : ["28810"],
		"dateCreated": "2017-09-25 10:16:08",
		"dateUpdated": "2017-09-29 11:26:21", 
		"refRelatedEntity": "POI-ENTITY-ID"
}
