=== galsenpro/data_model/schemas_v1.0/PointOfInteraction/iot_schemanca_PointOfInteraction.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$id": "http://example.com/example.json",
  "type": "object",
  "properties": {
    "id": {
      "$id": "/properties/id",
      "type": "string",
      "title": "The Id Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "SPOT-NCA-4326"
      ]
    },
    "type": {
      "$id": "/properties/type",
      "type": "string",
      "title": "The Type Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "SmartPointOfInteraction"
      ]
    },
    "category": {
      "$id": "/properties/category",
      "type": "array",
      "items": {
        "$id": "/properties/category/items",
        "type": "string",
        "title": "The 0 Schema.",
        "description": "An explanation about the purpose of this instance.",
        "default": "",
        "examples": [
          "information"
        ]
      }
    },
    "areaCovered": {
      "$id": "/properties/areaCovered",
      "type": "object",
      "properties": {
        "type": {
          "$id": "/properties/areaCovered/properties/type",
          "type": "string",
          "title": "The Type Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": "",
          "examples": [
            "Polygon"
          ]
        },
        "coordinates": {
          "$id": "/properties/areaCovered/properties/coordinates",
          "type": "array",
          "items": {
            "$id": "/properties/areaCovered/properties/coordinates/items",
            "type": "array",
            "items": {
              "$id": "/properties/areaCovered/properties/coordinates/items/items",
              "type": "array",
              "items": {
                "$id": "/properties/areaCovered/properties/coordinates/items/items/items",
                "type": "number",
                "title": "The 0 Schema.",
                "description": "An explanation about the purpose of this instance.",
                "default": 0,
                "examples": [
                  43.70180130004883
                ]
              }
            }
          }
        }
      }
    },
    "applicationUrl": {
      "$id": "/properties/applicationUrl",
      "type": "string",
      "title": "The Applicationurl Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "http://LinkOfApplication/"
      ]
    },
    "availability": {
      "$id": "/properties/availability",
      "type": "null",
      "title": "The Availability Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": null,
      "examples": [
        null
      ]
    },
    "refseeAlso": {
      "$id": "/properties/refseeAlso",
      "type": "array",
      "items": {
        "$id": "/properties/refseeAlso/items",
        "type": "string",
        "title": "The 0 Schema.",
        "description": "An explanation about the purpose of this instance.",
        "default": "",
        "examples": [
          "EVENT-PRO-NCA-8090"
        ]
      }
    }
  }
}

=== galsenpro/data_model/iot_testnca_datamodels_v1.0/iot_testnca_PointOfInteraction.json
{
	"id": "SPOT-NCA-4326",
	"type": "SmartPointOfInteraction",
	"category": ["information", "entertainment", "infotainment", "co-creation"],
	"areaCovered": {                           
		"type": "Polygon",
		"coordinates": [[
			[43.7018, 7.28081],
			[43.7018, 7.26389]
			]]
	},
	"applicationUrl": "http://LinkOfApplication/",
	"availability": null,
	"refseeAlso": [ "EVENT-PRO-NCA-8090", "EVENT-PUBLIC-NCA-8189"]
}
