=== galsenpro/data_model/schemas_v1.0/PointOfInterest/iot_schemanca_POI-Parking-OBJ001.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$id": "http://example.com/example.json",
  "type": "object",
  "properties": {
    "id": {
      "$id": "/properties/id",
      "type": "string",
      "title": "The Id Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "POI-Parking-OBJ001"
      ]
    },
    "type": {
      "$id": "/properties/type",
      "type": "string",
      "title": "The Type Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "PointOfInterest"
      ]
    },
    "name": {
      "$id": "/properties/name",
      "type": "string",
      "title": "The Name Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "MASSENA"
      ]
    },
    "description": {
      "$id": "/properties/description",
      "type": "string",
      "title": "The Description Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "Description du parking de MASSENA"
      ]
    },
    "address": {
      "$id": "/properties/address",
      "type": "object",
      "properties": {
        "postalCode": {
          "$id": "/properties/address/properties/postalCode",
          "type": "string",
          "title": "The Postalcode Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": "",
          "examples": [
            "06000"
          ]
        },
        "addressLocality": {
          "$id": "/properties/address/properties/addressLocality",
          "type": "string",
          "title": "The Addresslocality Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": "",
          "examples": [
            "NICE"
          ]
        },
        "addressRegion": {
          "$id": "/properties/address/properties/addressRegion",
          "type": "string",
          "title": "The Addressregion Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": "",
          "examples": [
            "Alpes Maritimes"
          ]
        },
        "addressCountry": {
          "$id": "/properties/address/properties/addressCountry",
          "type": "string",
          "title": "The Addresscountry Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": "",
          "examples": [
            "FR"
          ]
        },
        "streetAddress": {
          "$id": "/properties/address/properties/streetAddress",
          "type": "string",
          "title": "The Streetaddress Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": "",
          "examples": [
            "18 Avenue F�lix Faure"
          ]
        }
      }
    },
    "category": {
      "$id": "/properties/category",
      "type": "array",
      "items": {
        "$id": "/properties/category/items",
        "type": "string",
        "title": "The 0 Schema.",
        "description": "An explanation about the purpose of this instance.",
        "default": "",
        "examples": [
          "XXX, correspondant � Parking"
        ]
      }
    },
    "dateCreated": {
      "$id": "/properties/dateCreated",
      "type": "string",
      "title": "The Datecreated Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "2017-09-25T09:04:26Z"
      ]
    },
    "dateModified": {
      "$id": "/properties/dateModified",
      "type": "string",
      "title": "The Datemodified Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "2017-11-07T14:18:58.00Z"
      ]
    },
    "location": {
      "$id": "/properties/location",
      "type": "object",
      "properties": {
        "type": {
          "$id": "/properties/location/properties/type",
          "type": "string",
          "title": "The Type Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": "",
          "examples": [
            "Point"
          ]
        },
        "coordinates": {
          "$id": "/properties/location/properties/coordinates",
          "type": "array",
          "items": {
            "$id": "/properties/location/properties/coordinates/items",
            "type": "number",
            "title": "The 0 Schema.",
            "description": "An explanation about the purpose of this instance.",
            "default": 0,
            "examples": [
              7.2698564529418945
            ]
          }
        }
      }
    },
    "source": {
      "$id": "/properties/source",
      "type": "string",
      "title": "The Source Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "http://[SourceOfThePOI]"
      ]
    },
    "refSeeAlso": {
      "$id": "/properties/refSeeAlso",
      "type": "array",
      "items": {
        "$id": "/properties/refSeeAlso/items",
        "type": "string",
        "title": "The 0 Schema.",
        "description": "An explanation about the purpose of this instance.",
        "default": "",
        "examples": [
          "Parking-OBJ001"
        ]
      }
    }
  }
}

=== galsenpro/data_model/iot_testnca_datamodels_v1.0/PointOfInterest/iot_testnca_PointOfInterest.json
{
	"id": "IdOfPointInterest",
	"type": "PointOfInterest",
	"name": "POI's name",
	"description": "POI's description",
	"address": {
		"postalCode":"06000",
		"addressLocality": "NICE",
		"addressRegion": "Alpes Maritimes",
		"addressCountry": "FR",
		"streetAddress": "455 Promenade des anglais"
	},
	"category": ["113"],
	"dateModified": "2017-09-25T09:04:26Z",
	"dateCreated": "2017-09-25T09:04:26Z",
	"location": {
		"type": "Point",
		"coordinates": [
			-8.768460000000001,
			42.60214472222222
			]
	},
	"source": "http://[SourceOfThePOI]",
	"refSeeAlso": ["IdOfTheReferencedDataModel","PointOfInterest-Accommodation-74564"]
}

=== galsenpro/data_model/iot_testnca_datamodels_v1.0/iot_testnca_POI-Parking-OBJ001.json
{
	"id": "POI-Parking-OBJ001",
	"type": "PointOfInterest",
	"name": "MASSENA",
	"description": "Description du parking de MASSENA",
	"address": {
		"postalCode":"06000",
		"addressLocality": "NICE",
		"addressRegion": "Alpes Maritimes",
		"addressCountry": "FR",
		"streetAddress": "18 Avenue Félix Faure"
	},
	"category": ["XXX, correspondant à Parking"],
	"dateCreated": "2017-09-25T09:04:26Z",
	"dateModified": "2017-11-07T14:18:58.00Z",
	"location": {
		"type": "Point",
		"coordinates": [
			7.26985643, 43.69770086
			]
	},
	"source": "http://[SourceOfThePOI]",
	"refSeeAlso": ["Parking-OBJ001"]
}
