=== galsenpro/data_model/schemas_v1.0/PointOfInterest/iot_schemanca_PointOfInterest-Shopping-NCA-6587.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$id": "http://example.com/example.json",
  "type": "object",
  "properties": {
    "id": {
      "$id": "/properties/id",
      "type": "string",
      "title": "The Id Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "PointOfInterest-SHOP:75531"
      ]
    },
    "type": {
      "$id": "/properties/type",
      "type": "string",
      "title": "The Type Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "Shop"
      ]
    },
    "name": {
      "$id": "/properties/name",
      "type": "string",
      "title": "The Name Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "H & M"
      ]
    },
    "description": {
      "$id": "/properties/description",
      "type": "string",
      "title": "The Description Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "Boutique de pr�t � porter"
      ]
    },
    "url": {
      "$id": "/properties/url",
      "type": "string",
      "title": "The Url Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "http://www.hm.com/fr"
      ]
    },
    "faxNumber": {
      "$id": "/properties/faxNumber",
      "type": "string",
      "title": "The Faxnumber Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "0 805 08 88 65"
      ]
    },
    "telephone": {
      "$id": "/properties/telephone",
      "type": "string",
      "title": "The Telephone Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "+33(0)8 05 08 88 88"
      ]
    },
    "email": {
      "$id": "/properties/email",
      "type": "string",
      "title": "The Email Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "sav@hm.fr"
      ]
    },
    "paymentAccepted": {
      "$id": "/properties/paymentAccepted",
      "type": "array",
      "items": {
        "$id": "/properties/paymentAccepted/items",
        "type": "string",
        "title": "The 0 Schema.",
        "description": "An explanation about the purpose of this instance.",
        "default": "",
        "examples": [
          "1"
        ]
      }
    },
    "address": {
      "$id": "/properties/address",
      "type": "object",
      "properties": {
        "addressCountry": {
          "$id": "/properties/address/properties/addressCountry",
          "type": "string",
          "title": "The Addresscountry Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": "",
          "examples": [
            "FR"
          ]
        },
        "streetAddress": {
          "$id": "/properties/address/properties/streetAddress",
          "type": "string",
          "title": "The Streetaddress Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": "",
          "examples": [
            "455 Promenade des anglais"
          ]
        }
      }
    },
    "category": {
      "$id": "/properties/category",
      "type": "array",
      "items": {
        "$id": "/properties/category/items",
        "type": "string",
        "title": "The 0 Schema.",
        "description": "An explanation about the purpose of this instance.",
        "default": "",
        "examples": [
          "9"
        ]
      }
    },
    "alternateName": {
      "$id": "/properties/alternateName",
      "type": "string",
      "title": "The Alternatename Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        ""
      ]
    },
    "shopType": {
      "$id": "/properties/shopType",
      "type": "array",
      "items": {
        "$id": "/properties/shopType/items",
        "type": "string",
        "title": "The 0 Schema.",
        "description": "An explanation about the purpose of this instance.",
        "default": "",
        "examples": [
          "droguerie"
        ]
      }
    },
    "accessType": {
      "$id": "/properties/accessType",
      "type": "array",
      "items": {
        "$id": "/properties/accessType/items",
        "type": "string",
        "title": "The 0 Schema.",
        "description": "An explanation about the purpose of this instance.",
        "default": "",
        "examples": [
          "privateVehicle"
        ]
      }
    },
    "location": {
      "$id": "/properties/location",
      "type": "object",
      "properties": {
        "type": {
          "$id": "/properties/location/properties/type",
          "type": "string",
          "title": "The Type Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": "",
          "examples": [
            "Point"
          ]
        },
        "coordinates": {
          "$id": "/properties/location/properties/coordinates",
          "type": "array",
          "items": {
            "$id": "/properties/location/properties/coordinates/items",
            "type": "number",
            "title": "The 0 Schema.",
            "description": "An explanation about the purpose of this instance.",
            "default": 0,
            "examples": [
              43.69940185546875
            ]
          }
        }
      }
    },
    "source": {
      "$id": "/properties/source",
      "type": "null",
      "title": "The Source Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": null,
      "examples": [
        null
      ]
    },
    "refSeeAlso": {
      "$id": "/properties/refSeeAlso",
      "type": "array",
      "items": {
        "$id": "/properties/refSeeAlso/items",
        "type": "string",
        "title": "The 0 Schema.",
        "description": "An explanation about the purpose of this instance.",
        "default": "",
        "examples": [
          "Shopping-NCA-6587"
        ]
      }
    },
    "image": {
      "$id": "/properties/image",
      "type": "string",
      "title": "The Image Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "http://www.nicetourisme.com/public/resources/ref/entries/75531/gallery/h-m_172416.jpg"
      ]
    },
    "openingHours": {
      "$id": "/properties/openingHours",
      "type": "string",
      "title": "The Openinghours Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "10:00-19:30 - 11:00-19:00 (dimanche)"
      ]
    },
    "dateModified": {
      "$id": "/properties/dateModified",
      "type": "string",
      "title": "The Datemodified Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "2016-07-05 10:30:43"
      ]
    },
    "dateCreated": {
      "$id": "/properties/dateCreated",
      "type": "string",
      "title": "The Datecreated Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "2015-08-24 12:11:38"
      ]
    }
  }
}

=== galsenpro/data_model/datamodels_v1.0/PointOfInterest/iot_testnca_PointOfInterest-Shopping-NCA-6587.json
{
	"id": "PointOfInterest-SHOP:75531",
	"type": "Shop",
	"name": "H & M",
	"description": "Boutique de prêt à porter",
	"url" : "http://www.hm.com/fr",
	"faxNumber" : "0 805 08 88 65",
	"telephone" : "+33(0)8 05 08 88 88",
	"email": "sav@hm.fr",
	"paymentAccepted":["1", "2", "3"],
	"address": {
		"addressCountry": "FR",
		"streetAddress": "455 Promenade des anglais"
	},
	"category" : ["9", "5", "6"] ,
	"alternateName" : "",
	"shopType" : ["droguerie","cremerie"],
	"accessType": ["privateVehicle", "onFoot", "publicTransport"],
	"location": {
		"type": "Point",
		"coordinates": [
			43.6994,
			7.26831
			]
	},
	"source": null,
	"refSeeAlso": ["Shopping-NCA-6587"],
	"image" : "http://www.nicetourisme.com/public/resources/ref/entries/75531/gallery/h-m_172416.jpg",
	"openingHours": "10:00-19:30 - 11:00-19:00 (dimanche)",
	"dateModified": "2016-07-05 10:30:43",
	"dateCreated": "2015-08-24 12:11:38"
}
