=== galsenpro/data_model/schemas_v1.0/Device and DeviceDataModel/iot_schemanca_DeviceDataSensor-noiseLevel-208402176.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$id": "http://example.com/example.json",
  "type": "object",
  "properties": {
    "id": {
      "$id": "/properties/id",
      "type": "string",
      "title": "The Id Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "myDevice-noiseLevel-15440"
      ]
    },
    "type": {
      "$id": "/properties/type",
      "type": "string",
      "title": "The Type Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "DeviceDataSensor"
      ]
    },
    "category": {
      "$id": "/properties/category",
      "type": "string",
      "title": "The Category Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "sensor"
      ]
    },
    "name": {
      "$id": "/properties/name",
      "type": "string",
      "title": "The Name Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "Name of canal"
      ]
    },
    "description": {
      "$id": "/properties/description",
      "type": "string",
      "title": "The Description Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "Description du canal ou voie"
      ]
    },
    "location": {
      "$id": "/properties/location",
      "type": "object",
      "properties": {
        "type": {
          "$id": "/properties/location/properties/type",
          "type": "string",
          "title": "The Type Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": "",
          "examples": [
            "Point"
          ]
        },
        "coordinates": {
          "$id": "/properties/location/properties/coordinates",
          "type": "array",
          "items": {
            "$id": "/properties/location/properties/coordinates/items",
            "type": "number",
            "title": "The 0 Schema.",
            "description": "An explanation about the purpose of this instance.",
            "default": 0,
            "examples": [
              7.15521240234375
            ]
          }
        }
      }
    },
    "measurementTechnique": {
      "$id": "/properties/measurementTechnique",
      "type": "string",
      "title": "The Measurementtechnique Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "LDEN"
      ]
    },
    "label": {
      "$id": "/properties/label",
      "type": "string",
      "title": "The Label Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "Lden"
      ]
    },
    "unitCode": {
      "$id": "/properties/unitCode",
      "type": "string",
      "title": "The Unitcode Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "2N"
      ]
    },
    "unitText": {
      "$id": "/properties/unitText",
      "type": "string",
      "title": "The Unittext Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "dB"
      ]
    },
    "value": {
      "$id": "/properties/value",
      "type": "integer",
      "title": "The Value Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": 0,
      "examples": [
        7587
      ]
    },
    "dateObserved": {
      "$id": "/properties/dateObserved",
      "type": "string",
      "title": "The Dateobserved Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "2017-10-31T06:00:00"
      ]
    },
    "dateLastCalibration": {
      "$id": "/properties/dateLastCalibration",
      "type": "string",
      "title": "The Datelastcalibration Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "2017-10-31T06:00:00"
      ]
    },
    "height": {
      "$id": "/properties/height",
      "type": "null",
      "title": "The Height Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": null,
      "examples": [
        null
      ]
    },
    "channelState": {
      "$id": "/properties/channelState",
      "type": "string",
      "title": "The Channelstate Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "db_leqg"
      ]
    },
    "multiplier": {
      "$id": "/properties/multiplier",
      "type": "null",
      "title": "The Multiplier Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": null,
      "examples": [
        null
      ]
    },
    "measureFrequency": {
      "$id": "/properties/measureFrequency",
      "type": "null",
      "title": "The Measurefrequency Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": null,
      "examples": [
        null
      ]
    },
    "maxValue": {
      "$id": "/properties/maxValue",
      "type": "null",
      "title": "The Maxvalue Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": null,
      "examples": [
        null
      ]
    },
    "minValue": {
      "$id": "/properties/minValue",
      "type": "null",
      "title": "The Minvalue Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": null,
      "examples": [
        null
      ]
    },
    "siteGap": {
      "$id": "/properties/siteGap",
      "type": "null",
      "title": "The Sitegap Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": null,
      "examples": [
        null
      ]
    },
    "elevation": {
      "$id": "/properties/elevation",
      "type": "null",
      "title": "The Elevation Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": null,
      "examples": [
        null
      ]
    }
  }
}

=== galsenpro/data_model/iot_testnca_datamodels_v1.0/Device and DeviceDataModel/iot_testnca_DeviceDeviceDataModel-noiseLevel-208402176.json
{
	"id": "myDevice-noiseLevel-15440",
	"type": "DeviceDataModel",
	"category": "sensor",
	"name": "Name of canal",
	"description": "Description du canal ou voie",
	"location": {
		"type": "Point",
		"coordinates": [
			7.1552125224843621,
			43.660530261510573
		]
	},
	"measurementTechnique": "LDEN",
	"label": "Lden",
	"unitCode": "usedUniversalCode",
	"unitText": "TextOfusedUniversalCode",
	"value": 7587,
	"dateObserved": "2017-10-31T06:00:00",
	"dateLastCalibration": "2017-10-31T06:00:00",
	"height": null,
	"channelState": "db_leqg",
	"multiplier": null,
	"measureFrequency": null,
	"maxValue": null,
	"minValue": null,
	"siteGap": null,
	"elevation": null
}
