=== galsenpro/data_model/iot_testnca_schemas_v1.0/PointOfInterest/iot_testnca_PointOfInterest-Transport-NCA-30707.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$id": "http://example.com/example.json",
  "type": "object",
  "properties": {
    "id": {
      "$id": "/properties/id",
      "type": "string",
      "title": "The Id Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "PointOfInterest-Transport-30707"
      ]
    },
    "type": {
      "$id": "/properties/type",
      "type": "string",
      "title": "The Type Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "Transport"
      ]
    },
    "name": {
      "$id": "/properties/name",
      "type": "string",
      "title": "The Name Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "ACLOC LOCATION DE VOITURE ET UTILITAIRE | ACLOC"
      ]
    },
    "description": {
      "$id": "/properties/description",
      "type": "string",
      "title": "The Description Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "MAJONE ...."
      ]
    },
    "url": {
      "$id": "/properties/url",
      "type": "string",
      "title": "The Url Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "http://www.acloc.fr"
      ]
    },
    "faxNumber": {
      "$id": "/properties/faxNumber",
      "type": "string",
      "title": "The Faxnumber Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "+33(0)4 93 80 06 27"
      ]
    },
    "telephone": {
      "$id": "/properties/telephone",
      "type": "string",
      "title": "The Telephone Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "+33(0)4 93 80 08 00"
      ]
    },
    "email": {
      "$id": "/properties/email",
      "type": "string",
      "title": "The Email Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "acloc@hotmail.fr"
      ]
    },
    "address": {
      "$id": "/properties/address",
      "type": "object",
      "properties": {
        "addressCountry": {
          "$id": "/properties/address/properties/addressCountry",
          "type": "string",
          "title": "The Addresscountry Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": "",
          "examples": [
            "FR"
          ]
        },
        "streetAddress": {
          "$id": "/properties/address/properties/streetAddress",
          "type": "string",
          "title": "The Streetaddress Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": "",
          "examples": [
            "455 Promenade des anglais"
          ]
        }
      }
    },
    "language": {
      "$id": "/properties/language",
      "type": "array",
      "items": {
        "$id": "/properties/language/items",
        "type": "string",
        "title": "The 0 Schema.",
        "description": "An explanation about the purpose of this instance.",
        "default": "",
        "examples": [
          "1"
        ]
      }
    },
    "location": {
      "$id": "/properties/location",
      "type": "object",
      "properties": {
        "type": {
          "$id": "/properties/location/properties/type",
          "type": "string",
          "title": "The Type Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": "",
          "examples": [
            "Point"
          ]
        },
        "coordinates": {
          "$id": "/properties/location/properties/coordinates",
          "type": "array",
          "items": {
            "$id": "/properties/location/properties/coordinates/items",
            "type": "number",
            "title": "The 0 Schema.",
            "description": "An explanation about the purpose of this instance.",
            "default": 0,
            "examples": [
              7.263440132141113
            ]
          }
        }
      }
    },
    "proximity": {
      "$id": "/properties/proximity",
      "type": "array",
      "items": {
        "$id": "/properties/proximity/items",
        "type": "string",
        "title": "The 0 Schema.",
        "description": "An explanation about the purpose of this instance.",
        "default": "",
        "examples": [
          "Gare SNCF"
        ]
      }
    },
    "category": {
      "$id": "/properties/category",
      "type": "array",
      "items": {
        "$id": "/properties/category/items",
        "type": "string",
        "title": "The 0 Schema.",
        "description": "An explanation about the purpose of this instance.",
        "default": "",
        "examples": [
          "10"
        ]
      }
    },
    "sectors": {
      "$id": "/properties/sectors",
      "type": "null",
      "title": "The Sectors Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": null,
      "examples": [
        null
      ]
    },
    "living": {
      "$id": "/properties/living",
      "type": "object",
      "properties": {
        "roomCount": {
          "$id": "/properties/living/properties/roomCount",
          "type": "integer",
          "title": "The Roomcount Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": 0,
          "examples": [
            0
          ]
        },
        "roomBathCount": {
          "$id": "/properties/living/properties/roomBathCount",
          "type": "integer",
          "title": "The Roombathcount Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": 0,
          "examples": [
            0
          ]
        },
        "roomShowerCount": {
          "$id": "/properties/living/properties/roomShowerCount",
          "type": "integer",
          "title": "The Roomshowercount Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": 0,
          "examples": [
            0
          ]
        },
        "suiteCount": {
          "$id": "/properties/living/properties/suiteCount",
          "type": "integer",
          "title": "The Suitecount Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": 0,
          "examples": [
            0
          ]
        },
        "studioCount": {
          "$id": "/properties/living/properties/studioCount",
          "type": "integer",
          "title": "The Studiocount Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": 0,
          "examples": [
            0
          ]
        },
        "apartmentCount": {
          "$id": "/properties/living/properties/apartmentCount",
          "type": "integer",
          "title": "The Apartmentcount Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": 0,
          "examples": [
            0
          ]
        },
        "roomAccessibleCount": {
          "$id": "/properties/living/properties/roomAccessibleCount",
          "type": "integer",
          "title": "The Roomaccessiblecount Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": 0,
          "examples": [
            0
          ]
        },
        "singleCount": {
          "$id": "/properties/living/properties/singleCount",
          "type": "integer",
          "title": "The Singlecount Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": 0,
          "examples": [
            0
          ]
        },
        "doubleCount": {
          "$id": "/properties/living/properties/doubleCount",
          "type": "integer",
          "title": "The Doublecount Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": 0,
          "examples": [
            0
          ]
        },
        "tripleCount": {
          "$id": "/properties/living/properties/tripleCount",
          "type": "integer",
          "title": "The Triplecount Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": 0,
          "examples": [
            0
          ]
        },
        "twinsCount": {
          "$id": "/properties/living/properties/twinsCount",
          "type": "integer",
          "title": "The Twinscount Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": 0,
          "examples": [
            0
          ]
        },
        "familyCount": {
          "$id": "/properties/living/properties/familyCount",
          "type": "integer",
          "title": "The Familycount Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": 0,
          "examples": [
            0
          ]
        },
        "area": {
          "$id": "/properties/living/properties/area",
          "type": "integer",
          "title": "The Area Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": 0,
          "examples": [
            0
          ]
        },
        "typeLiving": {
          "$id": "/properties/living/properties/typeLiving",
          "type": "null",
          "title": "The Typeliving Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": null,
          "examples": [
            null
          ]
        },
        "floor": {
          "$id": "/properties/living/properties/floor",
          "type": "integer",
          "title": "The Floor Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": 0,
          "examples": [
            0
          ]
        },
        "bedroomCount": {
          "$id": "/properties/living/properties/bedroomCount",
          "type": "integer",
          "title": "The Bedroomcount Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": 0,
          "examples": [
            1
          ]
        },
        "sleepsCount": {
          "$id": "/properties/living/properties/sleepsCount",
          "type": "integer",
          "title": "The Sleepscount Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": 0,
          "examples": [
            4
          ]
        },
        "furnishedRoomCount": {
          "$id": "/properties/living/properties/furnishedRoomCount",
          "type": "integer",
          "title": "The Furnishedroomcount Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": 0,
          "examples": [
            2
          ]
        }
      }
    },
    "tariffs": {
      "$id": "/properties/tariffs",
      "type": "null",
      "title": "The Tariffs Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": null,
      "examples": [
        null
      ]
    },
    "capacity": {
      "$id": "/properties/capacity",
      "type": "object",
      "properties": {
        "indoor": {
          "$id": "/properties/capacity/properties/indoor",
          "type": "integer",
          "title": "The Indoor Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": 0,
          "examples": [
            0
          ]
        },
        "outdoor": {
          "$id": "/properties/capacity/properties/outdoor",
          "type": "integer",
          "title": "The Outdoor Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": 0,
          "examples": [
            0
          ]
        },
        "roomCount": {
          "$id": "/properties/capacity/properties/roomCount",
          "type": "integer",
          "title": "The Roomcount Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": 0,
          "examples": [
            0
          ]
        },
        "seated": {
          "$id": "/properties/capacity/properties/seated",
          "type": "integer",
          "title": "The Seated Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": 0,
          "examples": [
            0
          ]
        },
        "cocktail": {
          "$id": "/properties/capacity/properties/cocktail",
          "type": "integer",
          "title": "The Cocktail Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": 0,
          "examples": [
            0
          ]
        }
      }
    },
    "closures": {
      "$id": "/properties/closures",
      "type": "object",
      "properties": {
        "closureDay": {
          "$id": "/properties/closures/properties/closureDay",
          "type": "string",
          "title": "The Closureday Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": "",
          "examples": [
            "Dimanche"
          ]
        },
        "closureSpan": {
          "$id": "/properties/closures/properties/closureSpan",
          "type": "string",
          "title": "The Closurespan Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": "",
          "examples": [
            "Toute la journï¿½e"
          ]
        }
      }
    },
    "spaces": {
      "$id": "/properties/spaces",
      "type": "null",
      "title": "The Spaces Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": null,
      "examples": [
        null
      ]
    },
    "openingHours": {
      "$id": "/properties/openingHours",
      "type": "string",
      "title": "The Openinghours Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "8:00-23:00 (lundi au samedi) - 10:00-23:00 (dimanche)"
      ]
    },
    "closing": {
      "$id": "/properties/closing",
      "type": "string",
      "title": "The Closing Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "01/12-30/04"
      ]
    },
    "source": {
      "$id": "/properties/source",
      "type": "null",
      "title": "The Source Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": null,
      "examples": [
        null
      ]
    },
    "dateCreated": {
      "$id": "/properties/dateCreated",
      "type": "string",
      "title": "The Datecreated Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "2015-07-21 15:30:03"
      ]
    },
    "dateUpdated": {
      "$id": "/properties/dateUpdated",
      "type": "string",
      "title": "The Dateupdated Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "2017-08-30 17:31:02"
      ]
    },
    "refSeeAlso": {
      "$id": "/properties/refSeeAlso",
      "type": "array",
      "items": {
        "$id": "/properties/refSeeAlso/items",
        "type": "string",
        "title": "The 0 Schema.",
        "description": "An explanation about the purpose of this instance.",
        "default": "",
        "examples": [
          "Transport-NCA-2017"
        ]
      }
    }
  }
}

=== galsenpro/data_model/iot_testnca_datamodels_v1.0/PointOfInterest/iot_testnca_PointOfInterest-Transport-NCA-30707.json
{
	"id": "PointOfInterest-Transport-30707",
	"type": "Transport",
	"name": "ACLOC LOCATION DE VOITURE ET UTILITAIRE | ACLOC",
	"description": "MAJONE ....", 
	"url" : "http://www.acloc.fr",
	"faxNumber" : "+33(0)4 93 80 06 27",
	"telephone" : "+33(0)4 93 80 08 00",
	"email": "acloc@hotmail.fr",
	"address": {
		"addressCountry": "FR",
		"streetAddress": "455 Promenade des anglais"
	},
	"language": ["1", "2", "3"],
	"location": {
		"type": "Point",
		"coordinates": [
			7.26344, 
			43.7124
			]
	},
	"proximity" : ["Gare SNCF", "Acropolis", "Port", "Fabron", "Jean Médecin", "Gambetta", "Nice Est", "Centre Ville"],
	"category": ["10"],
	"sectors" : null, 
	"living" : {
		"roomCount" : 0,
		"roomBathCount" : 0,
		"roomShowerCount" :0,
		"suiteCount" : 0,
		"studioCount" : 0,
		"apartmentCount" : 0,
		"roomAccessibleCount" :0,
		"singleCount": 0,
		"doubleCount" :0,
		"tripleCount" :0,
		"twinsCount" : 0,
		"familyCount" : 0,
		"area" : 0,
		"typeLiving" : null,
		"floor" : 0,
		"bedroomCount" :1,
		"sleepsCount" :4,
		"furnishedRoomCount" :2
	},
	"tariffs" : null,
	"capacity" : {
		"indoor": 0,
		"outdoor": 0,
		"roomCount": 0,
		"seated": 0,
		"cocktail" : 0
	},
	"closures" : {
		"closureDay" : "Dimanche",
		"closureSpan" : "Toute la journée"
	},
	"spaces" : null,
	"openingHours" : "8:00-23:00 (lundi au samedi) - 10:00-23:00 (dimanche)",
	"closing" : "01/12-30/04",
	"source": null,
	"dateCreated": "2015-07-21 15:30:03",
	"dateUpdated": "2017-08-30 17:31:02", 
	"refSeeAlso": ["Transport-NCA-2017"]
}
