=== galsenpro/data_model/iot_testnca_schemas_v1.0/PointOfInterest/iot_testnca_POI_Air-Quality-Station-24011-081.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$id": "http://example.com/example.json",
  "type": "object",
  "properties": {
    "id": {
      "$id": "/properties/id",
      "type": "string",
      "title": "The Id Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "POI_Air-Quality-Station-24011-081"
      ]
    },
    "type": {
      "$id": "/properties/type",
      "type": "string",
      "title": "The Type Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "PointOfInterest"
      ]
    },
    "name": {
      "$id": "/properties/name",
      "type": "string",
      "title": "The Name Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "NICE OUEST BOTANIQUE"
      ]
    },
    "category": {
      "$id": "/properties/category",
      "type": "array",
      "items": {
        "$id": "/properties/category/items",
        "type": "string",
        "title": "The 0 Schema.",
        "description": "An explanation about the purpose of this instance.",
        "default": "",
        "examples": [
          "Valeur correspondant Ã  AirQualityStation dans le dictionnaire"
        ]
      }
    },
    "location": {
      "$id": "/properties/location",
      "type": "object",
      "properties": {
        "type": {
          "$id": "/properties/location/properties/type",
          "type": "string",
          "title": "The Type Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": "",
          "examples": [
            "Point"
          ]
        },
        "coordinates": {
          "$id": "/properties/location/properties/coordinates",
          "type": "array",
          "items": {
            "$id": "/properties/location/properties/coordinates/items",
            "type": "string",
            "title": "The 0 Schema.",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
              "+0071240.09"
            ]
          }
        }
      }
    },
    "refSeeAlso": {
      "$id": "/properties/refSeeAlso",
      "type": "array",
      "items": {
        "$id": "/properties/refSeeAlso/items",
        "type": "string",
        "title": "The 0 Schema.",
        "description": "An explanation about the purpose of this instance.",
        "default": "",
        "examples": [
          "Air-Quality-Station-24011-081"
        ]
      }
    },
    "source": {
      "$id": "/properties/source",
      "type": "string",
      "title": "The Source Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "http://datasource"
      ]
    }
  }
}

=== galsenpro/data_model/iot_testnca_datamodels_v1.0/PointOfInterest/iot_testnca_POI_Air-Quality-Station-24030-081.json
{
	"id": "POI_Air-Quality-Station-24030-081",
	"type": "PointOfInterest",
	"name": "NICE OUEST BOTANIQUE",
	"category": ["Valeur correspondant Ã  AirQualityStation dans le dictionnaire"],
	"location": {
		"type": "Point",
		"coordinates": [
			"+0071240.09",
			"+433927.89"
			]
	},
	"refSeeAlso":["Air-Quality-Station-24030-081"],
	"source": "http://datasource"
}
