=== galsenpro/data_model/schemas_v1.0/Environment/iot_schemanca_WaterLevelAndRiverFlow-201711071221.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$id": "http://example.com/example.json",
  "type": "object",
  "properties": {
    "id": {
      "$id": "/properties/id",
      "type": "string",
      "title": "The Id Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "WaterLevelAndRiverFlow-201711071221"
      ]
    },
    "type": {
      "$id": "/properties/type",
      "type": "string",
      "title": "The Type Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "WaterLevelAndRiverFlow"
      ]
    },
    "entity": {
      "$id": "/properties/entity",
      "type": "string",
      "title": "The Entity Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "Y6042010"
      ]
    },
    "dateLastValueReported": {
      "$id": "/properties/dateLastValueReported",
      "type": "string",
      "title": "The Datelastvaluereported Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "2016-06-29T15:59:09.22Z"
      ]
    },
    "location": {
      "$id": "/properties/location",
      "type": "object",
      "properties": {
        "coordinates": {
          "$id": "/properties/location/properties/coordinates",
          "type": "array",
          "items": {
            "$id": "/properties/location/properties/coordinates/items",
            "type": "number",
            "title": "The 0 Schema.",
            "description": "An explanation about the purpose of this instance.",
            "default": 0,
            "examples": [
              7.2698564529418945
            ]
          }
        },
        "type": {
          "$id": "/properties/location/properties/type",
          "type": "string",
          "title": "The Type Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": "",
          "examples": [
            "Point"
          ]
        }
      }
    },
    "measurand": {
      "$id": "/properties/measurand",
      "type": "array",
      "items": {
        "$id": "/properties/measurand/items",
        "type": "string",
        "title": "The 0 Schema.",
        "description": "An explanation about the purpose of this instance.",
        "default": "",
        "examples": [
          "H, Hauteur"
        ]
      }
    },
    "H": {
      "$id": "/properties/H",
      "type": "string",
      "title": "The H Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "-0.086"
      ]
    },
    "Q": {
      "$id": "/properties/Q",
      "type": "string",
      "title": "The Q Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": [
        "7.700"
      ]
    }
  }
}

=== galsenpro/data_model/schemas_v1.0/waterObserved/iot_schemanca_WaterLevelAndRiverFlow-201711071221.json
{
	"id": "WaterLevelAndRiverFlow-201711071221",
	"type": "WaterLevelAndRiverFlow",
	"entity": "Y6042010",
	"dateLastValueReported": "2016-06-29T15:59:09.22Z",
	"location": {
		"coordinates": [7.26985643, 43.69770086],
		"type": "Point"
	},
	"measurand": [ "H, Hauteur", "Q, Quantité en m3"],
	"H": "-0.086",
	"Q":"7.700"
}
